### ISSUE TITLE
Health check creates zombie processes when Crate is slow

### ISSUE THREAD

**Issue by kbolino** [crate/docker-crate#113]
If the health check curl command takes longer than the health check timeout (default is 30 seconds, I believe), then docker will kill the shell running the health check command but not the child processes of that shell, i.e. curl. So in cases where Crate is slow to respond, the health check leaves behind zombie processes that never get reaped. This will eventually fill up the PID table not only in the container but on the docker host machine as well. The simplest solution would probably be to make PID 1 something like [tini](https://github.com/krallin/tini), which is available in the Alpine Linux package repositories. The end result would be adding/modifying the Dockerfile akin to the following:

```dockerfile
# ...
RUN apk add tini

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["/docker-entrypoint.sh", "crate"]
```

I may be able to make a PR for this at a later time if needed.

**Comment by kbolino** [comment]
Another possible solution would be to set `--max-time` on the curl command and ensure the health check has a slightly longer timeout than that. Possible configuration:

```dockerfile
HEALTHCHECK --timeout=30s --interval=30s CMD curl -f --max-time 25 http://$(hostname):4200
```

**Comment by Autophagy** [comment]
Thank you for reporting this! I prefer your first suggestion of using tini for reaping zombie processes - I will create a PR.

**Comment by Autophagy** [comment]
@kbolino We've added `--max-time` to the curl command to combat the zombie processes, and it should be part of the next CrateDB release. Thanks again for reporting! :sparkles:
