### ISSUE TITLE
crash shell is missing inside 3.1.x images

### ISSUE THREAD

**Issue by berlic** [crate/docker-crate#121]
Since `crash` is not distributed as part of CrateDB release tarball anymore, it will be nice to add `crash` standalone into Dockerfile.

I have some broken automation scenarios with latest images because of this:
> "exec: \"crash\": executable file not found in $PATH"

**Comment by kovrus** [comment]
Hi @berlic ,

We've added `crash` to the crate docker image. It will be available in the next testing release.
