### ISSUE TITLE
how to disable elasticsearch syscall filter

### ISSUE THREAD

**Issue by neuroserve** [crate/docker-crate#126]
I'm not deploying on Linux (but a local Triton setup, which uses lx-branded zones), thus there's no Linux kernel, or seccomp and thus the syscall filter is obsolete. I've read in the elasticsearch docs, that the syscall filter can be disabled in elasticsearch.yml. 
Is there a way to disable the syscall filter in the docker-crate variant?  Going through the components in the Dockerfile, I haven't found an elasticsearch.yml to add this parameter to, in order to rebuild the container and try to deploy it.
 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap are also not needed, but I could remove these easily from the docker-entrypoint.sh
But where would I disable the syscall filtering?

**Comment by mfussenegger** [comment]
You should be able to pass the option directly via `docker run` to crate. `docker run ... crate -Cbootstrap.system_call_filter=false`

**Comment by neuroserve** [comment]
Works - Thx.
