### ISSUE TITLE
image for 3.3.6 not built

### ISSUE THREAD

**Issue by jaimeventura** [crate/docker-crate#171]
I was searching for version 3.3.6 (as im facing a memory issue), but it seems the image hasn't been  built.
Due to breaking changes from 3.x to 4.x, im restricted version 3.x
Thank you

**Comment by marregui** [comment]
Hola Jaime,

What version are you on?, would you be able to provide a little bit of context?

Thank you in advance,

**Comment by jaimeventura** [comment]
Sorry about that.
Im using 3.3.5, the one available [here](https://hub.docker.com/_/crate), single instance.
Im using CRATE as DB for [quantumleap](https://github.com/smartsdk/ngsi-timeseries-api) which, at the moment, doesnt support 4.x.

About the issue im having, Im getting a few of those on the logs:
>[WARN ][i.c.e.e.c.s.RamAccountingQueue] [Torrione dei Longerin] Memory limit for breaker [operations_log] was exceeded. Queue [RamAccountingQueue[68862f51-a356-4952-b8cf-26b0a5c5400b]] is cleared.

Usually crate starts slowing down, and it even crashed twice (no stack trace, so it might be related to docker and not crate itself).
This was after i changed the heap size from the default 512M to 2G, so it may be the GC kicking in.
Anyway,  my goal was to update it to the latest 3.x, and then try to debug the issue further.
Thanks

**Comment by marregui** [comment]
Hi Jaime,

**Comment by marregui** [comment]
Hi Jaime,

Thank you.

**Comment by marregui** [comment]
Found out why https://github.com/smartsdk/ngsi-timeseries-api/issues/256

**Comment by jaimeventura** [comment]
>I would suggest to increase it.
I will, thanks!

>In the meantime, we will push out 3.3.6
That would be great. 

About the issue im experimenting, I'll share my findings once/if i realize its a bug.
Cheers

**Comment by marregui** [comment]
Hi Jaime,

Image crate/crate:3.3.6 has been pushed (docker run -p 4200:4200 crate/crate:3.3.6).

Yes! please, it would be great if you shared your findings. If it is ok with you I will proceed to close this issue. 

Have a great day.

**Comment by jaimeventura** [comment]
Hey @marregui,
Thank you so much.

Any particular reason why you pushed the image  to [crate/crate (a nightly build of the official Docker image)](https://hub.docker.com/r/crate/crate), instead of [create (official Repo)](https://hub.docker.com/_/crate/)?

Regards.
