### ISSUE TITLE
Crash does not work in Crate:3.3.5 (89de81728a9d)

### ISSUE THREAD

**Issue by profijoeln** [crate/docker-crate#185]
Crash does not work in new Crate:3.3.5, ImageID: 89de81728a9d.

Expected:
```
crash
CONNECT OK
cr>
```

Running command 'crash' gives an error instead:
`/usr/bin/env: python3: No such file or directory`

Previously I have seen this work in at least following 3.3.5 image:
`crate:sha256:1220d3a66ba7434b40edd63308e7ebb931f7d20dfc03a7f40f24846525d96261`

Tested on Ubuntu machines, in Docker and Kubernetes.

Steps to reproduce:
Run container
`sudo docker run --name test crate:3.3.5`
Exec inside the container
`sudo docker exec -it test /bin/bash`
Use crash
`crash`

**Comment by kovrus** [comment]
@profijoeln thank you for reporting the issue. It should be resolved once https://github.com/docker-library/official-images/pull/8585 is merged and the official-image is built.

**Comment by kovrus** [comment]
The 3.3.5 image with the fix is available in the official docker images.
