### ISSUE TITLE
Not able store password for docker crate image

### ISSUE THREAD

**Issue by gayathrisandra** [crate/docker-crate#214]
I have added password based authentication for crate and tried to reuse that image. When this image is reused, passwords are not getting stored. Please help me to fix this issue.

**Comment by amotl** [comment]
Dear @gayathrisandra,

the user account table is part of the database content [^1]. The Docker image only contains CrateDB's runtime components, for persisting data, it is advised to mount the data directory to your host machine [^2].

I think for pre-provisioning user accounts, another mechanism will be required.

With kind regards,
Andreas.

[^1]: https://crate.io/docs/crate/reference/en/5.0/admin/user-management.html
[^2]: https://crate.io/docs/crate/tutorials/en/latest/containers/docker.html#persistent-data-directory

**Comment by amotl** [comment]
I think it is safe to close this issue. Please let us know if you have further questions on this topic.
