### ISSUE TITLE
Reconsider installation of `crash`/provide a minimal Docker image

### ISSUE THREAD

**Issue by hammerhead** [crate/docker-crate#219]
With `crash` and `openssl`, we currently install two packages that are not strictly needed to operate CrateDB inside a container.

For edge environments with limited internet bandwidth, it can be relevant to keep the image size to a minimum.

If neither `crash` nore `openssl` is installed, the whole `RUN yum install [...]` command can be removed, which reduces the image size (uncompressed) from 672 MB to 599 MB (11% saving).

In a first short discussion, it was not clear if any cloud components potentially rely on one of the two packages.

See also #218 for an attempt of removing `openssl`.

Possible options to consider:
* Remove the packages, if there is no specific use case
* Create multiple image variants. For example, keep the current image as-is and create an additional `minimal` image that doesn't include any components that aren't strictly required for running CrateDB
* There is also a minimal Almalinux image that could be interesting, as CrateDB already comes with a bundled JDK and there are no further dependencies:
  > It is designed for applications that come with their own dependencies bundled (e.g. NodeJS, Python).

**Comment by amotl** [comment]
> There is also a minimal Almalinux image that could be interesting.

We have not been able to use it, because it did not include `yum`, which was needed. We just learned to use `microdnf` instead [^1]. When also omitting `crash`, this patch would get the image size down to 532 MB.

```diff
diff --git a/Dockerfile.j2 b/Dockerfile.j2
index ea7216a..26f5d9d 100644
--- a/Dockerfile.j2
+++ b/Dockerfile.j2
@@ -5,13 +5,13 @@
 # https://github.com/crate/docker-crate
 #

-FROM almalinux:9
+FROM almalinux:9-minimal

 # Install prerequisites and package updates and clean up repository indexes again
-RUN yum install -y yum-utils \
-    && yum makecache \
-    && yum install -y python3 python3-pip openssl \
-    && yum clean all \
+RUN true \
+    && microdnf update \
+    && microdnf install --nodocs --assumeyes gzip shadow-utils tar \
+    && microdnf clean all \
     && rm -rf /var/cache/yum

 # Install CrateDB
@@ -32,16 +32,6 @@ RUN groupadd crate \
     && tar -xf {{ CRATE_TAR_GZ }} -C /crate --strip-components=1 \
     && rm {{ CRATE_TAR_GZ }}

-# Install crash
-RUN curl -fSL -O {{ CRASH_URL }} \
-    && curl -fSL -O {{ CRASH_URL }}.asc \
-    && export GNUPGHOME="$(mktemp -d)" \
-    && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 90C23FC6585BC0717F8FBFC37FAAE51A06F6EAEB \
-    && gpg --batch --verify crash_standalone_{{ CRASH_VERSION }}.asc crash_standalone_{{ CRASH_VERSION }} \
-    && rm -rf "$GNUPGHOME" crash_standalone_{{ CRASH_VERSION }}.asc \
-    && mv crash_standalone_{{ CRASH_VERSION }} /usr/local/bin/crash \
-    && chmod +x /usr/local/bin/crash
```

[^1]: https://wiki.almalinux.org/containers/docker-images.html#almalinux-minimal

**Comment by amotl** [comment]
This patch, still including `crash`, will bring the image size down to 565 MB.
```diff
diff --git a/Dockerfile.j2 b/Dockerfile.j2
index ea7216a..72770c7 100644
--- a/Dockerfile.j2
+++ b/Dockerfile.j2
@@ -5,13 +5,12 @@
 # https://github.com/crate/docker-crate
 #

-FROM almalinux:9
+FROM almalinux:9-minimal

 # Install prerequisites and package updates and clean up repository indexes again
-RUN yum install -y yum-utils \
-    && yum makecache \
-    && yum install -y python3 python3-pip openssl \
-    && yum clean all \
+RUN true \
+    && microdnf install --nodocs --assumeyes gzip python3 python3-pip openssl shadow-utils tar \
+    && microdnf clean all \
     && rm -rf /var/cache/yum
```

**Comment by amotl** [comment]
We will provide a minimal/slim image at a later point in time, see https://github.com/crate/docker-crate/pull/222#issuecomment-1523449819 ff.
