### ISSUE TITLE
2.1.5 refuses to start up due to memory settings

### ISSUE THREAD

**Issue by reversefold** [crate/docker-crate#85]
Using no special settings
```
docker run -p 4200:4200 -p 4300:4300 -p 5432:5432 crate crate -Cnetwork.host=_site_
```
I get the following:
```
[2017-08-21T20:55:45,964][INFO ][o.e.b.BootstrapChecks    ] [Ortler] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed
[1]: initial heap size [268435456] not equal to maximum heap size [524288000]; this can cause resize pauses and prevents mlockall from locking the entire heap
```

**Comment by reversefold** [comment]
I could only get this to work using `-e CRATE_JAVA_OPTS="-Xms1024m -Xmx1024m"` as in:
```
docker run -e CRATE_JAVA_OPTS="-Xms1024m -Xmx1024m" -p 4200:4200 -p 4300:4300 -p 5432:5432 crate crate -Cnetwork.host=_site_
```
JAVA_OPTIONS environment variable did not work. It would make sense to me for this to be defaulted to a fixed heap size by default so that no manual configuration is needed.

**Comment by srinijalagam** [comment]
latest version of docker run was failing even after setting JAVA_OPTIONS with below error message

bootstrap checks failed
max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]

this [https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode](url) help to set max 

after that it works fine.

**Comment by joemoe** [comment]
hi @reversefold, @srinijalagam, this is a known issue, there is already a fix that will be released with the next hotfix. thanks for reporting.

**Comment by joemoe** [comment]
using the environment var `CRATE_HEAP_SIZE` as documented here, this should work.
https://crate.io/docs/crate/guide/best_practices/docker.html
