### ISSUE TITLE
Travis-ci and CrateDB version 2.x

### ISSUE THREAD

**Issue by Igor-lkm** [crate/docker-crate#88]
Hello Folks, thank you for the container :)

I can not make version 2.x work with travis-ci 🤔 

* Working config for version 1.x https://github.com/megastef/node-crate/blob/master/.travis.yml < it is ok
```
before_install:
  - docker pull crate:1.1.6
  - docker run -d -p 4200:4200 -p 4300:4300 crate:1.1.6
```

* With version 2.x I have problems.
Config: https://github.com/megastef/node-crate/blob/ded61fbde0bed3ee4f3fa3c1c1399a13a7f74fdb/.travis.yml I have tried different options (like this https://stackoverflow.com/questions/45121456/unable-to-access-port-inside-docker)
```
before_install:
  - docker pull crate
  - docker run -d -p 4200:4200 -p 4300:4300 crate crate -Ccluster.name=my_cluster -Cnetwork.host=_site_
```

Which results in:
![image](https://user-images.githubusercontent.com/6287367/29788978-ceb9f366-8c34-11e7-813f-46e99b0297fb.png)

(https://travis-ci.org/megastef/node-crate/jobs/269288302)

Thank you for any help!

**Comment by mikethebeer** [comment]
@Igor-lkm  Docker has a side-effect that its networking hides the containers from the networking stack on the host machine. From Crate 1.1.6 to 2.1 the network stack has changed. To have the equivalent to 1.1.x you need to set `network.host` to `0.0.0.0` that CrateDB listens to all ipv4-addresses on the local machine.

**Comment by mikethebeer** [comment]
@Igor-lkm Please also check if you fullfilled the [Bootstrap Checks](https://crate.io/docs/crate/guide/best_practices/bootstrap_checks.html) that got introduced. If Crate does not get bind to localhost those checks get enabled and Crate only starts if their check have been successful.

**Comment by Igor-lkm** [comment]
@mikethebeer thank you!

Works like a charm!

Valid `.travis.yml`:

```
sudo: required

language: node_js
node_js:
  - "node"
  - "6"
  - "7"
  - "8"

services:
  - docker

before_install:
  - docker pull crate:2.1.5
  - docker run --name crate -d --memory 2g --env CRATE_HEAP_SIZE=1g -p 4200:4200 -p 4300:4300 crate:2.1.5 crate -Ccluster.name=cluster -Clicense.enterprise=false -Cnetwork.host=0.0.0.0

script:
  - npm test
```
