### ISSUE TITLE
Docker image not working

### ISSUE THREAD

**Issue by zopyx** [crate/docker-crate#9]
Status: Downloaded newer image for crate:latest
exec: "-p": executable file not found in $PATHFATA[0232] Error response from daemon: Cannot start container d42b08a9e5800df03564b2da93c107870f511e990b8321fdac429e1bff774755: exec: "-p": executable file not found in $PATH

**Comment by chaudum** [comment]
hi @zopyx 
could you please paste the full `docker run` command that you used? also, what host system are you running?
thanks,
christian

**Comment by zopyx** [comment]
^Cajung@demo:~$  docker run crate -p 4200:4200
exec: "-p": executable file not found in $PATHFATA[0022] Error response from daemon: Cannot start container a31100cfeb4700da3048562ff719c216636765cd5f05a169d87acb4f63e225b9: exec: "-p": executable file not found in $PATH



ajung@demo:~$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
ajung@demo:~$ docker info
Containers: 33
Images: 245
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 313
Execution Driver: native-0.2
Kernel Version: 3.13.0-44-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 2
Total Memory: 5.829 GiB
Name: demo.xml-director.info
ID: LTA5:NIZF:ZRHM:V6GM:SPMV:GKDE:WKUN:NZC7:MYRF:IMHU:BZC3:G6NH
Username: zopyx
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

**Comment by jodok** [comment]
@zopyx, you need to specify the arguments/options before the command. `docker run -p 4200:4200 crate` works fine

**Comment by zopyx** [comment]
Your docs are wrong

https://crate.io/docs/

Can you update the docs about exposing the data directory as a volume?

**Comment by zopyx** [comment]
Found the docs in the docker-crate repo

**Comment by jodok** [comment]
you're right. website is wrong. will fix it. github description or https://registry.hub.docker.com/_/crate/ is right.

**Comment by jodok** [comment]
for the record, website fixed. https://github.com/crate/crate-web/commit/9f05773b21adba8777ac582a8e8dd8efcdddc7e5
