### ISSUE TITLE
ppc64le dockerhub images

### ISSUE THREAD

**Issue by vaibhavsood** [crate/docker-crate#90]
Hi, I'm looking to enable docker containers for packages like crate for multiple architectures on dockerhub, starting off with a focus on ppc64le. Wanted to check on the work that will be involved to do that

I have locally been able to successfully test ppc64le changes to the dockerfiles in this repo - changes for enabling additional arch would be minimum.

Would like to know how a multi-arch image for this can be initiated? The official images have this method for enabling multi-arch : https://github.com/docker-library/official-images#multiple-architectures, however this repo isnt an official image yet. Would the first step be to make this an official image or are there any other ways the dockerhub crate image can be enabled for ppc64le?

**Comment by joemoe** [comment]
hi @vaibhavsood, 

can you please clarify some things:

* what are you trying to achieve?
* what would you need that for?
* what is the use case behind?

also:

* the cratedb docker image is an official one: https://github.com/docker-library/official-images/blob/master/library/crate

thanks.

**Comment by vaibhavsood** [comment]
hi @joemoe , thanks for the reply!

Answers are inline

what are you trying to achieve?
>> Have a cratedb docker official image for ppc64le. Basically have a image out here: https://hub.docker.com/u/ppc64le/

what would you need that for?
>> The steps to have a official multi-arch image are out here: : https://github.com/docker-library/official-images#multiple-architectures. Basically for cratedb, the current dockerfile (in this repo, for intel) may need additions for ppc64le. I'm willing to work on them, want to check first here whether you are okay with accepting those additions

what is the use case behind?
>> Have cratedb docker images enabled for ppc64le and posted to dockerhub, the changes to the dockerfiles shouldnt be much (i have locally built a ppc64le cratedb container)

Please let me know any questions/comments, thanks!

**Comment by vaibhavsood** [comment]
Oops, i see a similar issue opened for arm, https://github.com/crate/docker-crate/issues/83, as per the last comment from @tianon , need to wait for alpine image to be enabled for multi-arch

Guess will have to wait for that

**Comment by mfussenegger** [comment]
> what are you trying to achieve?
>> Have a cratedb docker official image for ppc64le. Basically have a image out here: https://hub.docker.com/u/ppc64le/

Would you then actually use that image, and if so, on what kind of platform?
So far this sounds like having an image for the sake of having an image.

**Comment by vaibhavsood** [comment]
Hi @mfussenegger,

The use case for this would be to have the crate image for additional arch's available on dockerhub. My agenda here is to expand images under dockerhub for additional arch's although i dont really have a specific use for it in mind

However since crate already has an intel official image, the effort to extend it to other arch's should'nt be significant. I am willing to work it for ppc64le and doing it for other arches should be similar

**Comment by vaibhavsood** [comment]
Hi, want to check back on this, since alpine image is multi-arch this and https://github.com/crate/docker-crate/issues/83 can be resolved

Only thing needed would be to update alpine to 3.6 (since dockerhub ppc64le does not have a 3.5 alpine image)

**Comment by mfussenegger** [comment]
I think having images for the sake of having images is not a priority for us and we've limited resources. We'd like to see some interest from people who intend to use CrateDB.

For us supporting an official image also means to do some basic testing with each release to make sure it works correctly. So this is not only about updating the alpine base image and calling it done.

We'll keep this open and encourage potential users to upvote it to see for us if there is more interest.

**Comment by vaibhavsood** [comment]
Hi @mfussenegger ,

Want to check back once more regarding this

This is not really related to creating an official image but rather running crate on ppc64le. I tried running the Dockerfile from this repo as-is on a ppc64le machine, i see there are some platform dependencies in it for eg. sigar installation fails on power 

Want to check enablement of ppc64le as a platform for crate. I'm at IBM and can help with getting a public CI nightly build setup for crate on ppc64le (assuming that's a good idea for crate :smile:  )

Will it be useful to have this? thanks!

**Comment by mfussenegger** [comment]
Since this issue has originally be raised there have been some changes to CrateDB which might help running it on ppc64le. (E.g. we removed sigar). 

So maybe it would be worth trying again if there is still interest on your side. From our side we haven't really heard other users request support for ppc64le. So official support is still not high on our priority list. But if there are some minor issues that block it from working we'd be happy to fix them.
